### ISSUE TITLE
No WK0.xml file

### ISSUE THREAD

**Issue by chivesrs** [Jineapple/WololoKingdoms#10]
boost::filesystem::copy_file: The system cannot find the file specified: "resources/WK0.xml"

Here is a list of files in my resources/ directory:
https://i.imgur.com/5SEyl8L.png

**Comment by chivesrs** [comment]
Closing the installer and reinstalling fixed it.

**Comment by Jineapple** [comment]
Do you know if you had Steam open the first time you ran the installer? Any game open? Do you own all DLCs?
