### ISSUE TITLE
Error in converting characters: EILSEQ

### ISSUE THREAD

**Issue by SP458** [Jineapple/WololoKingdoms#12]
This error happens at 83% while applying the DAT patches (offline installation). I own all HD DLCs and the French version of AoC.

**Comment by Jineapple** [comment]
Thank you for the report, I'll look into that. Did you have "Create offline installation" checked or not?

**Comment by SP458** [comment]
Yes, it was checked.

**Comment by SP458** [comment]
I've made progress with this issue: even after changing the language of HD to English and selecting English in the installer, the issue persists. Maybe it's due to the AoC game not being English.

**Comment by Jineapple** [comment]
This should be fixed with the 2.6 update I'll be uploading soon
