### ISSUE TITLE
Resolution Glitch

### ISSUE THREAD

**Issue by Hichokei** [Jineapple/WololoKingdoms#14]
When I first installed in my coputer all was fine, but in my laptop I'll find with this error
![image](https://user-images.githubusercontent.com/30747303/29007147-68e02a1c-7afd-11e7-9ee8-c11198ab34b1.png)

After making a few changes, I'll realize that the native resolution for the laptop 1366x768 doesn't work fine, only works in 1280x720 and 800x600.

I don't know if you can extend the compatibility for more resolutions.

Thanks

**Comment by Jineapple** [comment]
Thanks for the report! I'll look into this.
Question: Does this happen with all civs? Can you try this with Britons, Slavs and Vietnamese and tell me if it happens with all of them?

Edit: After looking into it, I suspect this is an older bug. Do you use the HD compatibilty patch to play on Voobly? If yes, did you run it _after_ running the WK installer? That would cause this problem. The WK installer renames the "compatslp" folder, which creates interface issues. Running the comp patch after the installer would put that folder back.
You will get an error message saying the comp patch isn't installed when entering a Voobly lobby and the compatslp folder can't be found, but that message can safely be ignored. Hopefully that check will be adjusted in a future Voobly update. For now, if there's a "compatslp" folder in your Age2HD directory, delete/rename that (Alternatively, run the WK installer again)

**Comment by kcisino** [comment]
I'm also having a similar issue.  But it only occurs when specific civs are being used.  I've been keeping a log of civs that are experiencing the issue.  Right now, I've only noticed it with Mongols, Indians and Huns.
![tearingmongols](https://user-images.githubusercontent.com/30800606/29028269-b06ef1d4-7b51-11e7-9bf5-ddad990d7424.jpg)

EDIT* I pulled the "compatslp" and "compatslp2" folder out of the Age2HD file and it seems to be working fine!

**Comment by Hichokei** [comment]
When I rename the compatslp and compatslp2 folder the same Voobly warning appear: 
![image](https://user-images.githubusercontent.com/30747303/29038821-515f5e42-7ba9-11e7-996e-9162b16ae9e9.png)
I hope that soon Voobly solve this Issue.

**Comment by Jineapple** [comment]
Yes, it's normal that this warning appears, you can safely ignore it. It's up to Voobly to update their game diagnostic check so you don't have to click this away every time, hopefully that happens soon.

Good to know that this isn't a new bug :)
