### ISSUE TITLE
Treb Bug

### ISSUE THREAD

**Issue by ALLCAPSYEAH** [Jineapple/WololoKingdoms#15]
Right Clicking with trebs results in them walking to targeted building instead of unpacking/firing.

WololoKingdoms mod
Patch: v1.5 Beta 9 Build 5565
Example attached, trebs were manually unpacked to fire.

Game ended with OOS. 
Restore worked fine.
[rec.20170902-004504.zip](https://github.com/Jineapple/WololoKingdoms/files/1272013/rec.20170902-004504.zip)

**Comment by Jineapple** [comment]
The treb not attacking was a bug I fixed - Unfortunately, the version number wasn't updated even though the dat file changed, which leads to an OOS when two people have different dat files. I will upload a 2.5 version soon.

**Comment by ALLCAPSYEAH** [comment]
Ah just unfortunate timing, thanks Jine!

**Comment by Jineapple** [comment]
This is fixed with 2.5
