### ISSUE TITLE
Memb can't cast Viper/DauT Bo21 due to different 2.5 WK version

### ISSUE THREAD

**Issue by coffenbacher** [Jineapple/WololoKingdoms#17]
https://www.twitch.tv/membtv

Not sure what is happening exactly https://www.twitch.tv/videos/174932769

**Comment by Jineapple** [comment]
This was because Viper&Daut were playing on WK with 5.4 balance in steam, while Memb re-ran the installer after 5.5 had been released. The timing of the patch release was unfortunate. It's something to keep in mind if there are other dat changes with a coming patch.
