### ISSUE TITLE
problems with installation 

### ISSUE THREAD

**Issue by Burunito** [Jineapple/WololoKingdoms#18]
There was an exception! Make sure you don't have the game running, or have any game files opened, then try running the installer again.
If this still happens, please pass this error on to Jineapple: boost::filesystem::remove: Acceso denegado: "c:\program files (x86)\steam\SteamApps\common\Age2HD\Voobly Mods/AOC/Data Mods\WololoKingdoms\Script.Rm\Amazonia.rms"

this keep happens and i dont know why

**Comment by Jineapple** [comment]
Try deleting that file or the entire script.rm folder as shown there before running the installer. Sometimes a lock remains on a file or something and it won't allow the installer to replace the files. Haven't been able to figure the exact cause out yet.

**Comment by sirjamesnice** [comment]
Hi

I have a similar problem:

There was an exception! Make sure you don't have the game running, or have any game files opened, then try running the installer again.
If this still happens, please pass this error on to Jineapple: boost::filesystem::remove_all: Toegang geweigerd: "c:\program files (x86)\steam\steamapps\common\age2hd\Voobly Mods/AOC/Data Mods\WololoKingdoms FE\Data"

But as you mentioned above, I wanted to delete the file/folder, only it does not exist.. I do have a folder WololoKingdoms AK.. What should I do? I bought AOE and the expansions through steam. I have the latest userpatch (1.5) and downloaded the 2.5 WK installer zipfile.

**Comment by Jineapple** [comment]
You could try running the installer after a reboot, maybe the file locks can be resolved that way.

**Comment by sirjamesnice** [comment]
the problem is, i can't remove the folder. It says i'm not an administrator and do not have the rights, although I'm logged in with a profile that has administrator rights. Anyways, I assume that's not an HD problem, but still I can't reboot this way.

Because I would like to try and reinstall everything, AOEII, HD, Voobly and WK

**Comment by sirjamesnice** [comment]
@Jineapple haha I just found a solution. I had to install WK version 2.4 first and then I could install 2.5 without any problems! It does work. Maybe a fix for other players too..
