### ISSUE TITLE
Error instalation

### ISSUE THREAD

**Issue by infa444** [Jineapple/WololoKingdoms#20]
There was an exception! Make sure you don't have the game running, or have any game files opened, then try running the installer again.
If this still happens, please pass this error on to Jineapple: boost::filesystem::file_size: El sistema no puede encontrar el archivo especificado: "C:\Program Files (x86)\Steam/steamapps/common/Age2HD/resources/_common/drs/gamedata_x2/51131.slp"

**Comment by Jineapple** [comment]
I can look at this in detail in a few days, but it sounds like your HD installation is missing this file. Can you try verifying your game files and running the installer again?

You can also try running the installer with the option to copy special maps deselected, as a possible temporary fix

**Comment by infa444** [comment]
Verifing my game files I solved the problem. There were two missing files, Steam downloaded they again and finally I could run the WK installer.

Thank you!! :)

**Comment by Jineapple** [comment]
Great to hear :)
