### ISSUE TITLE
Problem with monks

### ISSUE THREAD

**Issue by VladVonCarstein** [Jineapple/WololoKingdoms#25]
Today, I was playing 2.7 version 1.5 R5 beta vs AI with khemers in arena and I notice a bug, the monks sometimes vanish and you can't click on them, especially when the monks put a relic in the monastery, occasionally they reappear, and others you never see more the monks.

I post a rec of the game, in the min 17:50  you can see clearly the bug, maybe a problem with the skin?
[rec.20171020-183040.zip](https://github.com/Jineapple/WololoKingdoms/files/1403578/rec.20171020-183040.zip)

**Comment by Jineapple** [comment]
When did you download the installer? This should already be fixed in the current version, it was a bunch of older slp files I forgot to remove. Also make sure that you are unpacking the zip into an empty folder to make sure those files aren't still there from an older version of the installer.

**Comment by VladVonCarstein** [comment]
I download the installer 2 days ago, but I overwriting files with the old version. I was testing delete the old files and reinstall, and seems that the problem is fixed, thanks.
