### ISSUE TITLE
wololokingdoms mod not found

### ISSUE THREAD

**Issue by qaws68** [Jineapple/WololoKingdoms#31]
I already run WololoKingdoms.exe  https://i.imgur.com/SijdHCn.jpg and I can find wololokingdoms folder in Age2HD/Voobly Mods/AOC/Data Mods : https://i.imgur.com/MEve1aX.jpg
but If I open room, it's not show WololoKingdoms in Mod Option https://i.imgur.com/p2rvJBC.jpg
https://i.imgur.com/he5lTyy.jpg
How do i solve this problem? 
I will be grateful for any help you can provide.

**Comment by Jineapple** [comment]
This looks like you have two AoE installations, with Voobly using a different than than what the WK installer used. Not sure why this would happen, but to fix it you can either copy the WK folders to the installation used by Voobly (probably a CD install, you can find it by clicking Help->Open Game Directory in a Voobly Lobby) and copying the WK folders to the Voobly Mod folders of that game directory.
Alternatively, you could change the directory Voobly uses for the game by renaming the gold game directory, and then pointing Voobly to C:\Program Files (x86)\Steam\steamapps\common\Age2HD\age2_x1\age2_x1.exe when it doesn't find the exe it previously used and asks you to locate it (Happens upon entering a lobby after renaming)

**Comment by qaws68** [comment]
Thanks for your help. Because it's my friend's problem, and it seems a little complicated that you advise the steps to fix it .The problem should on two AoE installations. So he remove old AOE installation version and reinstall voobly and WK again. Finally, WK is work. I appreciate for your instant reply and help!

**Comment by Jineapple** [comment]
Good to hear :)
