### ISSUE TITLE
Api error, i cant install wololo.

### ISSUE THREAD

**Issue by GonsuPeppaH** [Jineapple/WololoKingdoms#33]
Hello, i have Aoe2HD bought with all expansions, but i cant install wololo mod, i have steam open when i use the exe, tried to have the wololo directory in the Aoe2HD place and in other one. Also reinstaled Aoe2 and did the Verify integrity steam option but the same problem keep hapening.

**Comment by TriRem** [comment]
Hi, what is the error message the program is giving you ?

**Comment by GonsuPeppaH** [comment]
[![Screenshot from Gyazo](https://gyazo.com/93672165bde07a72affedd0311040770/raw)](https://gyazo.com/93672165bde07a72affedd0311040770)
[![Screenshot from Gyazo](https://gyazo.com/05a069d48f26efb64bc91d9fb90514fa/raw)](https://gyazo.com/05a069d48f26efb64bc91d9fb90514fa)

**Comment by TriRem** [comment]
Hi again,
Did you try restarting Steam ? If it didn't work, is Steam installed in the default location ?
