### ISSUE TITLE
Error while installing wk

### ISSUE THREAD

**Issue by Sirito** [Jineapple/WololoKingdoms#34]
There was an exception! Make sure you don't have the game running, or have any game files opened, then try running the installer again.
If this still happens, please pass this error on to Jineapple: boost::filesystem::is_empty: Das System kann die angegebene Datei nicht finden: "new_terrain_override\"

how can i get the missing file?

**Comment by TriRem** [comment]
Seems like the programs is looking for a file it can't find. In your WololoKingdms folder, do you have a new_terrain_override folder ? If yes is it empty ?

**Comment by Sirito** [comment]
Hell TriRem,
I checked my WK folders, especially the "new terrains", and it includes 29 data but there is is no new_terrain_override folder neither in the other WK related folders.

**Comment by TriRem** [comment]
Hi again, sorry for the delayed answer.
In the WololoKingdoms folder, create an empty folder and name it "new_terrain_override". Then running the installer should work, I don't know why the folder is missing.

**Comment by TabAli** [comment]
Hi, I got this error , any help ?
There was an exception! Make sure you don't have the game running, or have any game files opened, then try running the installer again.
If this still happens, please pass this error on to Jineapple: basic_string::_M_replace_aux

**Comment by Sirito** [comment]
No Problem @TriRem. Was busy, too. I created that folder and it worked. Unfortunately I had choosen the 2.7 and so I had to do all that again for 5.6/7 but I think that it finally works. Tested it with as spectator. Thanks!
