### ISSUE TITLE
Spanish - Labels with accents are wrongly displayed

### ISSUE THREAD

**Issue by NickCis** [Jineapple/WololoKingdoms#35]
Hi, when installing the Spanish language i got problems in the labels:

![image](https://user-images.githubusercontent.com/174561/35204686-98743ae4-ff0e-11e7-8d55-ecb1707e8c9c.png)

![image](https://user-images.githubusercontent.com/174561/35204698-ab47ff20-ff0e-11e7-9112-c208f52f2133.png)

The characters wrongly displayed are the ones with accent marks (á, é, í, ó, ú) or the _ñ_ letter. 

My guess is that the problem could be related with character encodings (The errors are similar to the ones you see when a web page loaded with the wrong character encoding, the page is send in utf8, but the browser thinks it is iso-8859-1 / latin-1).

I really do not know how wololo kindoms stores / retrieves this labels, if you give me some tips i could try to fix it :).

**Comment by TriRem** [comment]
Hi,
Seems like it's an encoding error, I'll come back to you when I get a fix :)

**Comment by NickCis** [comment]
The last 1.5 beta patch and then reinstalling wk fixed the issue!
