### ISSUE TITLE
Error running wololo kingdom

### ISSUE THREAD

**Issue by Caferuiza** [Jineapple/WololoKingdoms#36]
There was an exception! Make sure you don't have the game running, or have any game files opened, then try running the installer again.
If this still happens, please pass this error on to Jineapple: basic_string::substr: __pos (which is 6) > this->size() (which is 5)

**Comment by Jineapple** [comment]
Sorry I haven't replied to you sooner. Do you still get this issue?

**Comment by fedeOnGit** [comment]
i've got the same problem!

**Comment by Jineapple** [comment]
Is your game on steam updated (To Patch 5.7)? If yes, can you post the contents of log.txt after a run?

**Comment by tetrachromacy** [comment]
when WololoKingdoms runs it stops between 12% and 14% specifically while generating resource files i'll be very grateful if my problem got solved

**Comment by Jineapple** [comment]
This should be fixed in newer versions of the installer, in case you still get this, best create an issue at https://github.com/aoe2communitygithub/WololoKingdoms/issues
