### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by MillerTB** [Jineapple/WololoKingdoms#41]
I've tried the troubleshooting outlined in the README file. Maybe I'm missing something? Here is the error code. I don't understand why it can't find the file listed in the code because it is clearly in the folder. 

>system cannot find the file specified: "resources\WK3.xml", "C:\Program Files 
>(x86)\Steam\steamapps\common\Age2HD\Voobly Mods\AOC\Data Mods\WololoKingdoms\age2_x1.xml"

**Comment by MillerTB** [comment]
Copied the missing xml file out of a download of 5.7 and got this error message

```
There was an exception! Make sure you don't have the game running, or have any game files opened, then try running the installer again.
If this still happens, please pass this error on to Jineapple: boost::filesystem::file_size: The system cannot find the path specified
```

can't get WK to install and it's kind of a bummer

**Comment by Jineapple** [comment]
1. Make sure that you use the newest installer of 5.7.2, redownload that
2. Disable antivirus software during the installation, it might potentially trigger a false positive.
3. If that alone doesn't work, you might need to delete the old WololoKingdoms folders at C:\Program Files
(x86)\Steam\steamapps\common\Age2HD\Voobly Mods\AOC\Data Mods before running the installer to make sure that a previous failed installation doesn't mess up things. If you do that, make sure to back up your save games, maps, hotkey file and everything else you want to keep.

**Comment by Jineapple** [comment]
The 5.7.3 installer should give you a correct error message now
