### ISSUE TITLE
Cannot install wololo

### ISSUE THREAD

**Issue by muddassir-lateef** [Jineapple/WololoKingdoms#42]
WHen i try to install wololo i get his error
boost::filesystem::copy_file: The system cannot find the path specified, "age2_x1.xml"
plz fix this issue
i have wolo kingodms folder in aokhd folder and the directory i specifed in the software was the my aoc folder.plz help.
my email:muddassirlateef001@gmail.com

**Comment by Jineapple** [comment]
Is this with the most recent installer? It should say 5.7.2 (b). If not, please redownload it

**Comment by Jineapple** [comment]
Fixed an issue with this, you will get a proper error message with the next installer, probably telling you that the DLCs aren't properly installed.
