### ISSUE TITLE
Serious bug about Battle Elephant

### ISSUE THREAD

**Issue by a453712990** [Jineapple/WololoKingdoms#43]
In the HD version, the trampling damage of Southeast Asian Battle Elephant is half of the original damage, and in the WK version, the trampling damage of the Battle Elephant is equivalent to the original damage! This bug makes the Southeast Asian elephants seem too powerful against other melee units. Have you not found this bug? I hope the author can fix this bug in the next version.Thanks!

**Comment by Jineapple** [comment]
Thanks for the report, I'll see that this is looked at for the next update.
