### ISSUE TITLE
Some graphical errors in DLC textures. [with fix]

### ISSUE THREAD

**Issue by abductedPlatypus** [Jineapple/WololoKingdoms#44]
Hi,
While making some random maps I noticed some graphical bugs in some of the DLC textures, so I decided to remake some of them. Mainly the border of some textures was grey (even on top of grids in textures).
I also fixed some "grid revealing" (see: http://pixeljoint.com/forum/forum_posts.asp?TID=11299)

I hope I don't offend your artist. D:

I also included some automation files (for Photoshop) for future reference, and use for custom textures. If anything is missing or incomplete or have questions feel free to poke me. Though I should get a notification on GitHub.

Download them here (I'll keep 'em for at least a few months):
https://stack.abductedplatypus.com/s/braNgyy2uFOjq0S

Keep up the great work!

![texturechanges](https://user-images.githubusercontent.com/27150757/43554974-d341cf58-95f7-11e8-9724-fb138dcccd54.png)

I forgot to describe the problems, so the above images shows the two main problems I fixed.

**Comment by Jineapple** [comment]
This is great, thank you! No offense taken at all, I was aware of the issues when converting the textures but did not want to spend time on figuring out how to fix it :P

Will see that this is included in the next update!
