### ISSUE TITLE
Virus Result xD

### ISSUE THREAD

**Issue by Cyphierion** [Jineapple/WololoKingdoms#46]
![image](https://user-images.githubusercontent.com/35496928/44250150-1db85f00-a1a8-11e8-9cb9-bb2e8c46346f.png)

**Comment by Cyphierion** [comment]
Avast! Free Antivirus shows this up as a virus (False Positive,/etc)
I'm not a dumb kid like my father that screams and shits his pants when he sees an anti-virus popup.
Cheers matey!

**Comment by Jineapple** [comment]
Yeah, the updater downloads a new version of the WololoKingdoms.exe, some antivirus programs don't like a binary file being downloaded. Don't personally have the time to look into a solution.
One thing you can do is disable the auto-updater by deleting or renaming the WKUpdater.exe before running the installer (If you've already downloaded the latest version manually before)

**Comment by Cyphierion** [comment]
Perhaps a raw file data pull from a server (or even github) and rewriting itself or a new process

**Comment by Jineapple** [comment]
The new updater by Gregstein should hopefully work better for this. It's still possible that some antivirus software might get triggered anyway. In that case, make an exception for it and if possible send the file to their lab, so they can flag it as unproblematic.
