### ISSUE TITLE
Download link dead & what even is the current project?

### ISSUE THREAD

**Issue by chrmol** [Jineapple/WololoKingdoms#49]
This is what is set as the download link, but it just results in a 404? Also readme says that this isn't the current project but then it links back to this project?
[/Jineapple/AoE2CommunityGitHub/releases](https://github.com/Jineapple/AoE2CommunityGitHub/releases)

**Comment by gregstein** [comment]
Hello chrmol,

The WK binaries are available at https://github.com/AoE2CommunityGitHub/WololoKingdoms/releases

**Comment by Jineapple** [comment]
Where are you getting that link from? It should be set to the one gregstein posted everywhere.

**Comment by Jineapple** [comment]
Found the problematic link thanks to another report. Fixed :)
