### ISSUE TITLE
Defenitive Edition

### ISSUE THREAD

**Issue by hhirsch** [Jineapple/WololoKingdoms#53]
Will the DE-Civs and Balance come to WK? DE is reported to not run on Steam Play/Proton on Linux at all (HD and voobly/WK do) so the only reason for me to buy it would be if it came to WK.

**Comment by Jineapple** [comment]
This is something we're still discussing, but tentatively I would say no. At the very least, I would not buy DE until it's done.

The main issue apart from possible technical changes is that presumably there would a smaller playerbase left over of those not playing on the DE. We can only have DE civs for those who own DE but prefer playing Userpatch. This would most likely split the playerbase between those and the players who do not own DE at all. 

As the remaining playerbase will most likely be comparatively small already, introducing further splits by offering a DE option would probably do more harm than good. Maybe we can find a way to deal with this, but I don't have any good ideas right now.

**Comment by hhirsch** [comment]
That is actually good news for me. Would have felt bad to spend the money on a game that does neither run native nor through proton on GNU/Linux. I play WK almost daily. Thank you for the great work.
