### ISSUE TITLE
Contact me if you want to make a mod based on WK (e.g. no walls)

### ISSUE THREAD

**Issue by Jineapple** [Jineapple/WololoKingdoms#7]
Plan: Users can copy a dat file into the WololoKingdoms installer folder, along with a .txt file with the mod name, and it will generate a modded version. However, with no automatic distribution it's an issue to get people to use it.

**Comment by Jineapple** [comment]
After thinking about it, it doesn't make sense to have a solution that requires users to copy a dat file - Mod creators would have to get that dat file to mod users first. Instead, if someone has a Dat Mod based on WK, they can contact me and I will include it as an option in the installer

**Comment by Hichokei** [comment]
Hi Jineapple, I'm spanish and I'm making a special translation for the Age, where I'm adding more and useful informatión. Like other mods in engilsh like Pro mod.

My mod is currently in voobly http://www.voobly.com/gamemods/mod/829/Spanish-Eish-en-Beta but the information with the expansions changes a few things. I want to know how to make the two differents translations for use each one when we play with all the expansions or without them.

**Comment by Jineapple** [comment]
Hey, I'm sorry I didn't see this earlier. The WK installer actually already includes something like this with the detailed tooltips option, which is available for Spanish. If you still want to have your own mod for this, you can do this by adding a "Voobly Mods/AOC/Data Mods/WololoKingdoms" folder structure INSIDE your visual mod folder. That way, you can modify files if that particular data mod is loaded.
